"""Generate a taxonomy file from lalafo's live category tree.

Adding a vertical means writing a file under ``configs/categories/``.  Typing 125
brand ids by hand is how mistakes get in, so this module fetches the real tree
(``Api.CATEGORY_TREE``) and renders the skeleton: every leaf under a chosen root,
with its id, its Russian name and the ads_count the site reported at the time.

The two classification axes cannot be inferred from a name, so they are supplied by
the caller (``--type`` / ``--deal``) and meant to be hand-edited afterwards where a
branch really does split by deal — which is exactly the judgement a generator should
not be making for you.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

from .constants import Api
from .http_client import LalafoClient
from .logging_utils import get_logger

logger = get_logger(__name__)


def fetch_tree(client: LalafoClient) -> list[dict[str, Any]]:
    """The whole category forest, as lalafo serves it to its own frontend."""
    tree = client.get_json(Api.CATEGORY_TREE)
    if not isinstance(tree, list):
        raise RuntimeError(f"unexpected category tree payload: {type(tree).__name__}")
    return tree


def find(nodes: list[dict[str, Any]], category_id: int) -> dict[str, Any] | None:
    """Depth-first search for one category anywhere in the forest."""
    for node in nodes:
        if node.get("id") == category_id:
            return node
        found = find(node.get("children") or [], category_id)
        if found:
            return found
    return None


def leaves(node: dict[str, Any]) -> Iterator[dict[str, Any]]:
    """Every childless descendant — these are the crawl streams."""
    children = node.get("children") or []
    if not children:
        yield node
    for child in children:
        yield from leaves(child)


def render(
    node: dict[str, Any],
    *,
    vertical: str,
    property_type: str,
    deal: str,
    label_key: str | None = None,
) -> str:
    """Render a ready-to-edit taxonomy YAML for everything under ``node``."""
    found = sorted(leaves(node), key=lambda leaf: -(leaf.get("ads_count") or 0))
    if not found:
        raise ValueError(f"category {node.get('id')} has no leaves")

    lines = [
        f"# Taxonomy for lalafo.kg — «{node.get('name')}» (root {node.get('id')}).",
        "#",
        "# GENERATED by `make categories` — review before use. `type` and `deal` are",
        f"# stamped with the values you passed ({property_type} / {deal}); split them by",
        "# hand where the branch really does distinguish sale from rent or requests.",
        "#",
        "# `params` starts empty: unmapped params are transliterated, never dropped, so",
        "# a first crawl works as-is — then promote the ids you care about to clean",
        "# English column names.",
        "",
        f"vertical: {vertical}",
        f'title: "{node.get("name")}"',
        f"root_category: {node.get('id')}",
        f"site_path: {node.get('url') or '/'}",
        "",
        "special_params: {}",
        "",
        "params: {}",
        "",
        f"# {len(found)} leaf categories, biggest first "
        "(trailing number = ads at generation time).",
        "categories:",
    ]
    entries = []
    for leaf in found:
        name = _quote(str(leaf.get("name") or ""))
        label = f", {label_key}: {name}" if label_key else ""
        entries.append((
            f"  {leaf['id']}: {{type: {property_type}, deal: {deal}{label}, name: {name}}}",
            leaf.get("ads_count") or 0,
        ))
    width = max(len(text) for text, _ in entries)
    lines += [f"{text.ljust(width)}  # {count}" for text, count in entries]
    lines.append("")
    return "\n".join(lines)


def _quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
